services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: pipeline
      POSTGRES_PASSWORD: pipeline_user
      POSTGRES_DB: pipeline_pass
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data


volumes:
  pgdata: